### ISSUE TITLE
DbListener throws TrimmedDataAccess error when listening to the table stream

### ISSUE THREAD

**Issue by knightdna** [knightdna/java-dynamodb-stream#9]
The execution fails with the following error log

```
[sdk-async-response-3-1] ERROR co.novandi.diaz.client.DbStreamListener - Unable to listen to record changes. Reason: software.amazon.awssdk.services.dynamodb.model.TrimmedDataAccessException: The operation attempted to read past the oldest stream record in a shard. (Service: DynamoDbStreams, Status Code: 400, Request ID: 7e77f47e-74b2-43e2-893a-bbe26fdc0c7f)
Exception in thread "main" java.util.concurrent.CompletionException: software.amazon.awssdk.services.dynamodb.model.TrimmedDataAccessException: The operation attempted to read past the oldest stream record in a shard. (Service: DynamoDbStreams, Status Code: 400, Request ID: 7e77f47e-74b2-43e2-893a-bbe26fdc0c7f)
	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:62)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:181)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:167)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by knightdna** [comment]
Apparently there are few older shards which are ended already (they have `EndingSequenceNumber` value).

Here are some examples,
```
[main] INFO co.novandi.diaz.client.DbStreamListener - shard Shard(ShardId=shardId-00000001661417116593-8091403d, SequenceNumberRange=SequenceNumberRange(StartingSequenceNumber=000000000000000000001, EndingSequenceNumber=000000000000000000002))
[main] INFO co.novandi.diaz.client.DbStreamListener - shard Shard(ShardId=shardId-00000001661431550831-cd62281d, SequenceNumberRange=SequenceNumberRange(StartingSequenceNumber=000000000000000000004, EndingSequenceNumber=000000000000000000008), ParentShardId=shardId-00000001661417116593-8091403d)
[main] INFO co.novandi.diaz.client.DbStreamListener - shard Shard(ShardId=shardId-00000001661448994863-bbb5ca09, SequenceNumberRange=SequenceNumberRange(StartingSequenceNumber=000000000000000000010, EndingSequenceNumber=000000000000000000010), ParentShardId=shardId-00000001661431550831-cd62281d)
[main] INFO co.novandi.diaz.client.DbStreamListener - shard Shard(ShardId=shardId-00000001661489304015-5fe13dc4, SequenceNumberRange=SequenceNumberRange(StartingSequenceNumber=000000000000000000011, EndingSequenceNumber=000000000000000000011), ParentShardId=shardId-00000001661448994863-bbb5ca09)
[main] INFO co.novandi.diaz.client.DbStreamListener - shard Shard(ShardId=shardId-00000001661503852955-cd083a02, SequenceNumberRange=SequenceNumberRange(StartingSequenceNumber=000000000000000000012), ParentShardId=shardId-00000001661489304015-5fe13dc4)
```

We are unable to iterate the older shards by making a `GetShardIterator` request. It will throw that `TrimmedDataAccessException`. The error message also clearly states "The operation attempted to read past the oldest stream record in a shard".

We shall only iterate the current shard and filter the shards which doesn't have an `EndingSequenceNumber` value. From the example above, we can only iterate the latest shard with `shardId-00000001661503852955-cd083a02`.
